version: 0.0
os: linux

files:
  - source: /test.jsp
    destination: /home/ec2-user/tomcat/webapps/ROOT/
    #  - source: /springbootApp.jar
    #    destination: /home/ec2-user/

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: exam-start.sh
      timeout: 10
      runas: root
  ApplicationStop:
    - location: exam-stop.sh
      timeout: 10
      runas: root
