apiVersion: v1
kind: Service
metadata:
  name: sb-svc
spec:
  selector:
    app: spring
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8085 # Spring 애플리케이션의 포트가 8085이다.
  type: LoadBalancer
